In [0]:
import tensorflow as tf

In [0]:
layer = tf.keras.layers.Dense(100)


In [0]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs

    def build(self, input_shape):
        self.kernel = self.add_weight('kernel', shape = [int(input_shape[-1]), self.num_outputs])

    def call(self, input):
        return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)

In [0]:
# input_shape . kernel_shape
#  10x5 . 5x10

In [0]:
_ = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.

In [0]:
# making model with existing layers

In [0]:
class ResnetIdentifyBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentifyBlock, self).__init__(name = '')
        filter1, filter2, filter3 = filters

        self.conv2a = tf.keras.layers.Conv2D(filter1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()

        self.conv2b = tf.keras.layers.Conv2D(filter2, kernel_size, padding = 'same')
        self.bn2b = tf.keras.layers.BatchNormalization()

        self.conv2c = tf.keras.layers.Conv2D(filter3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()


    def call(self, input_tensor, training = False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training = training)

        x += input_tensor
        return tf.nn.relu(x)


block = ResnetIdentifyBlock(1, [1, 2, 3])

In [0]:
_ = block(tf.zeros([1, 2, 3, 3]))

#passing 2 sample of 3x3 length

In [16]:
block.layers

In [17]:
len(block.variables)

18

In [18]:
block.variables

[<tf.Variable 'resnet_identify_block/conv2d/kernel:0' shape=(1, 1, 3, 1) dtype=float32, numpy=
 array([[[[-0.7049488 ],
          [-0.69258803],
          [-0.8409063 ]]]], dtype=float32)>,
 <tf.Variable 'resnet_identify_block/conv2d/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'resnet_identify_block/batch_normalization/gamma:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Variable 'resnet_identify_block/batch_normalization/beta:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'resnet_identify_block/batch_normalization/moving_mean:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'resnet_identify_block/batch_normalization/moving_variance:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Variable 'resnet_identify_block/conv2d_1/kernel:0' shape=(1, 1, 1, 2) dtype=float32, numpy=array([[[[-0.25853682, -0.52469254]]]], dtype=float32)>,
 <tf.Variable 'resnet

In [19]:
block.summary()

Model: "resnet_identify_block"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              multiple                  4         
_________________________________________________________________
batch_normalization (BatchNo multiple                  4         
_________________________________________________________________
conv2d_1 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_1 (Batch multiple                  8         
_________________________________________________________________
conv2d_2 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_2 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
________________________________________________

In [0]:
# this can be done by

In [22]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(1, (1, 1), input_shape = (None, None, 3)))
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Conv2D(2, 1, padding = 'same'))
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Conv2D(3, (1, 1)))
model.add(tf.keras.layers.BatchNormalization())

model(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [23]:
model.summary

<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f8dced8b390>>