In [1]:
#setup for csv data

In [2]:
import tensorflow as tf
import numpy as np


In [3]:
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/eval.csv"

train_file_path = tf.keras.utils.get_file('train.csv', TRAIN_DATA_URL)
test_file_path = tf.keras.utils.get_file('eval.csv', TEST_DATA_URL)

In [6]:
#preciion with 3 decimal points
#easier to read
np.set_printoptions(precision=3, suppress=True)

In [7]:
LABEL_COLUMN = 'survived'
LABELS = [0, 1]

In [8]:
#to create a dataset from csv

In [9]:
def get_dataset(file_path, **kwargs):
    dataset = tf.data.experimental.make_csv_dataset(
        file_path, 
        batch_size = 5, #if the data id very large
        label_name = LABEL_COLUMN,
        na_value = '?',
        num_epochs = 1,
        ignore_errors = True,
        **kwargs 
    )
    
    return dataset

raw_train_data = get_dataset(train_file_path)
raw_test_data = get_dataset(test_file_path)

In [10]:
#it only shows the batch not the labels
def show_batch(dataset):
   
    for batch, label  in dataset.take(2):
        print(label.numpy())
        for key, values in batch.items():
            print(key, ':', values.numpy())


In [11]:
show_batch(raw_train_data)

[0 0 1 0 1]
sex : [b'male' b'male' b'female' b'male' b'female']
age : [34. 28. 27. 23. 28.]
n_siblings_spouses : [0 0 0 0 0]
parch : [0 0 0 0 0]
fare : [13.     8.05   7.925 13.     7.75 ]
class : [b'Second' b'Third' b'Third' b'Second' b'Third']
deck : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town : [b'Southampton' b'Southampton' b'Southampton' b'Southampton' b'Queenstown']
alone : [b'y' b'y' b'y' b'y' b'y']
[0 0 1 1 1]
sex : [b'male' b'male' b'female' b'female' b'male']
age : [18. 37. 30.  4. 35.]
n_siblings_spouses : [0 1 0 0 0]
parch : [0 0 0 2 0]
fare : [73.5   26.    12.475 22.025 26.288]
class : [b'Second' b'Second' b'Third' b'Third' b'First']
deck : [b'unknown' b'unknown' b'unknown' b'unknown' b'E']
embark_town : [b'Southampton' b'Southampton' b'Southampton' b'Southampton'
 b'Southampton']
alone : [b'y' b'n' b'y' b'n' b'y']


In [12]:
show_batch(raw_test_data)

[1 0 1 1 0]
sex : [b'female' b'male' b'male' b'male' b'male']
age : [28.   43.   32.    0.83 31.  ]
n_siblings_spouses : [1 0 0 1 1]
parch : [0 0 0 1 1]
fare : [52.     6.45   7.925 18.75  26.25 ]
class : [b'First' b'Third' b'Third' b'Second' b'Second']
deck : [b'C' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town : [b'Southampton' b'Southampton' b'Southampton' b'Southampton'
 b'Southampton']
alone : [b'n' b'y' b'y' b'n' b'n']
[1 1 0 0 1]
sex : [b'male' b'female' b'female' b'male' b'female']
age : [56. 28. 28. 28. 18.]
n_siblings_spouses : [0 1 0 0 0]
parch : [0 1 0 0 2]
fare : [35.5   22.358  8.05  22.525 79.65 ]
class : [b'First' b'Third' b'Third' b'Third' b'First']
deck : [b'A' b'F' b'unknown' b'unknown' b'E']
embark_town : [b'Cherbourg' b'Cherbourg' b'Southampton' b'Southampton' b'Southampton']
alone : [b'y' b'n' b'y' b'y' b'n']


In [13]:
#we can also select the particular columns as to make the dataset as shown

In [14]:
CSV_COLUMNS = ['survived', 'sex', 'age', 'n_siblings_spouses', 'parch', 'fare', 'class', 'deck', 'embark_town', 'alone']

#column_names are set as **kwargs
temp_dataset = get_dataset(train_file_path, column_names = CSV_COLUMNS)

show_batch(temp_dataset)

[1 1 0 0 1]
sex : [b'male' b'male' b'male' b'male' b'male']
age : [45. 32. 57. 28. 80.]
n_siblings_spouses : [0 0 0 0 0]
parch : [0 0 0 1 0]
fare : [26.55  56.496 12.35  33.    30.   ]
class : [b'First' b'Third' b'Second' b'Second' b'First']
deck : [b'unknown' b'unknown' b'unknown' b'unknown' b'A']
embark_town : [b'Southampton' b'Southampton' b'Queenstown' b'Southampton' b'Southampton']
alone : [b'y' b'y' b'y' b'n' b'y']
[0 0 0 0 1]
sex : [b'male' b'male' b'male' b'male' b'female']
age : [31. 18. 28. 11. 28.]
n_siblings_spouses : [0 0 0 5 0]
parch : [0 0 0 2 0]
fare : [10.5   73.5    7.225 46.9   33.   ]
class : [b'Second' b'Second' b'Third' b'Third' b'Second']
deck : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town : [b'Southampton' b'Southampton' b'Cherbourg' b'Southampton' b'Southampton']
alone : [b'y' b'y' b'y' b'n' b'y']


In [15]:
#data preprocessing

In [16]:
#iif the data is in the numeric format then its a good practice to pass that numeric data into a single vector format

In [17]:
SELECT_COLUMNS = ['survived', 'age', 'n_siblings_spouses', 'parch', 'fare']
DEFAULTS = [0, 0.0, 0.0, 0.0, 0.0]

temp_dataset = get_dataset(train_file_path, select_columns = SELECT_COLUMNS, column_defaults = DEFAULTS)

show_batch(temp_dataset)

[1 0 0 1 1]
age : [28. 28. 31. 38. 21.]
n_siblings_spouses : [1. 0. 0. 0. 2.]
parch : [0. 0. 0. 0. 2.]
fare : [ 16.1   221.779  50.496 227.525 262.375]
[1 0 0 0 0]
age : [24. 18. 45. 28. 51.]
n_siblings_spouses : [2. 0. 0. 0. 0.]
parch : [3. 0. 0. 0. 0.]
fare : [18.75   7.775  7.75   7.55   7.054]


In [18]:
#one of the many batches are collected here
example_batch, labels = next(iter(temp_dataset))

In [19]:
example_batch['age'].numpy()

array([18.,  4., 28., 28., 14.], dtype=float32)

In [20]:
labels.numpy()

array([0, 1, 0, 0, 0])

In [21]:
print([example_batch.values()])
print()
print(list(example_batch.values()))

[odict_values([<tf.Tensor: shape=(5,), dtype=float32, numpy=array([18.,  4., 28., 28., 14.], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 0., 8., 5.], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 0., 2., 2.], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 8.3  , 16.7  ,  8.458, 69.55 , 46.9  ], dtype=float32)>])]

[<tf.Tensor: shape=(5,), dtype=float32, numpy=array([18.,  4., 28., 28., 14.], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 0., 8., 5.], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 0., 2., 2.], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 8.3  , 16.7  ,  8.458, 69.55 , 46.9  ], dtype=float32)>]


In [22]:
labels

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 0, 0])>

In [23]:
#packing all both the features and labes in one into a single tuple kinda thinkg called dataset hhere,,,,,,,,hahahaah

def pack(features, label):
    return tf.stack(list(features.values()), axis = -1), label

In [24]:
packed_dataset = temp_dataset.map(pack)

for features, labels in packed_dataset.take(1):
    print(type(labels))
    print(features.numpy())
    print()
    print(labels.numpy())

<class 'tensorflow.python.framework.ops.EagerTensor'>
[[20.     0.     0.     7.229]
 [35.     0.     0.     7.05 ]
 [48.     0.     0.     7.854]
 [28.     0.     0.     7.896]
 [21.     0.     0.     7.796]]

[1 0 0 0 1]


In [25]:
#also we can pack the numeric data in a single column into a dataset

In [26]:
class PackNumericFeatures(object):
    def __init__(self, names):
        self.names = names

    def __call__(self, *args):
        features, labels = args
        numeric_features = [features.pop(name) for name in self.names]
        numeric_features = [tf.cast(feat, tf.float32) for feat in numeric_features]
        numeric_features = tf.stack(numeric_features, axis = -1)
        features['numeric'] = numeric_features

        return features, labels

In [27]:
NUMERIC_FEATURES = ['age','n_siblings_spouses','parch', 'fare']

packed_train_data = raw_train_data.map(PackNumericFeatures(NUMERIC_FEATURES))
packed_test_data = raw_test_data.map(PackNumericFeatures(NUMERIC_FEATURES))

In [28]:
show_batch(packed_train_data)

[0 0 1 0 0]
sex : [b'male' b'male' b'female' b'male' b'male']
class : [b'Third' b'Third' b'First' b'Third' b'Second']
deck : [b'unknown' b'unknown' b'unknown' b'unknown' b'D']
embark_town : [b'Southampton' b'Southampton' b'Cherbourg' b'Southampton' b'Cherbourg']
alone : [b'n' b'n' b'y' b'y' b'y']
numeric : [[24.     1.     0.    16.1  ]
 [33.     1.     1.    20.525]
 [30.     0.     0.    31.   ]
 [59.     0.     0.     7.25 ]
 [36.     0.     0.    12.875]]
[0 0 0 1 0]
sex : [b'male' b'male' b'male' b'female' b'male']
class : [b'Second' b'Third' b'Third' b'Second' b'First']
deck : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town : [b'Southampton' b'Southampton' b'Queenstown' b'Southampton' b'Cherbourg']
alone : [b'y' b'y' b'n' b'n' b'y']
numeric : [[35.     0.     0.    26.   ]
 [28.     0.     0.     7.896]
 [ 4.     4.     1.    29.125]
 [33.     1.     2.    27.75 ]
 [71.     0.     0.    49.504]]


In [29]:
example_batch, labels_batch = next(iter(packed_train_data)) 

In [30]:
#normalization
#continuous data should always be normalized

In [31]:
import pandas as pd


In [32]:
desc = pd.read_csv(train_file_path)[NUMERIC_FEATURES].describe()
desc

age  n_siblings_spouses       parch        fare
count  627.000000          627.000000  627.000000  627.000000
mean    29.631308            0.545455    0.379585   34.385399
std     12.511818            1.151090    0.792999   54.597730
min      0.750000            0.000000    0.000000    0.000000
25%     23.000000            0.000000    0.000000    7.895800
50%     28.000000            0.000000    0.000000   15.045800
75%     35.000000            1.000000    0.000000   31.387500
max     80.000000            8.000000    5.000000  512.329200

In [33]:
desc.T

count       mean        std   min      25%      50%  \
age                 627.0  29.631308  12.511818  0.75  23.0000  28.0000   
n_siblings_spouses  627.0   0.545455   1.151090  0.00   0.0000   0.0000   
parch               627.0   0.379585   0.792999  0.00   0.0000   0.0000   
fare                627.0  34.385399  54.597730  0.00   7.8958  15.0458   

                        75%       max  
age                 35.0000   80.0000  
n_siblings_spouses   1.0000    8.0000  
parch                0.0000    5.0000  
fare                31.3875  512.3292

In [34]:
MEAN = np.array(desc.T['mean'])
STD = np.array(desc.T['std'])

In [35]:
MEAN

array([29.631,  0.545,  0.38 , 34.385])

In [36]:
#center the data
def normalize_numeric_data(data, mean, std):
    return (data-mean)/std

In [47]:
import functools

normalizer = functools.partial(normalize_numeric_data, mean = MEAN, std = STD)

#this is also other way to create a numeric column
numeric_column = tf.feature_column.numeric_column('numeric', normalizer_fn = normalizer, shape = [len(NUMERIC_FEATURES)])
numeric_columns = [numeric_column]

In [48]:
numeric_columns[0]

NumericColumn(key='numeric', shape=(4,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function normalize_numeric_data at 0x0000014D123AAF28>, mean=array([29.631,  0.545,  0.38 , 34.385]), std=array([12.512,  1.151,  0.793, 54.598])))

In [49]:
example_batch['numeric']

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[36.   ,  1.   ,  0.   , 26.   ],
       [28.   ,  1.   ,  2.   , 23.45 ],
       [ 6.   ,  0.   ,  1.   , 12.475],
       [28.   ,  0.   ,  0.   , 26.   ],
       [18.   ,  1.   ,  1.   , 20.212]], dtype=float32)>

In [50]:
numeric_layer  = tf.keras.layers.DenseFeatures(numeric_columns)
numeric_layer(example_batch).numpy()

array([[ 0.509,  0.395, -0.479, -0.154],
       [-0.13 ,  0.395,  2.043, -0.2  ],
       [-1.889, -0.474,  0.782, -0.401],
       [-0.13 , -0.474, -0.479, -0.154],
       [-0.93 ,  0.395,  0.782, -0.26 ]], dtype=float32)

In [86]:
#categorical_data


In [87]:
CATEGORIES = {
    'sex': ['male', 'female'],
    'class' : ['First', 'Second', 'Third'],
    'deck' : ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'embark_town' : ['Cherbourg', 'Southhampton', 'Queenstown'],
    'alone' : ['y', 'n']
}


In [88]:
categorical_columns = []

for feature, vocab in CATEGORIES.items():
    cat_col = tf.feature_column.categorical_column_with_vocabulary_list(key = feature, vocabulary_list = vocab)
    categorical_columns.append(tf.feature_column.indicator_column(cat_col))

In [89]:
categorical_columns

[IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='sex', vocabulary_list=('male', 'female'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='class', vocabulary_list=('First', 'Second', 'Third'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='deck', vocabulary_list=('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='embark_town', vocabulary_list=('Cherbourg', 'Southhampton', 'Queenstown'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='alone', vocabulary_list=('y', 'n'), dtype=tf.string, default_value=-1, num_oov_buckets=0))]

In [91]:
categorical_layer = tf.keras.layers.DenseFeatures(categorical_columns)
print(categorical_layer(example_batch).numpy())

[[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [92]:
#combining all the feature layers

In [94]:
preprocessing_layer = tf.keras.layers.DenseFeatures(categorical_columns + numeric_columns)


In [98]:
print(preprocessing_layer(example_batch).numpy()[0])

[ 1.     0.     0.     0.     1.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.    -0.37  -0.474
 -0.479 -0.63   1.     0.   ]


In [99]:
#building the model

In [100]:
model = tf.keras.Sequential(preprocessing_layer)
model.add(tf.keras.layers.Dense(128, activation = 'relu'))
model.add(tf.keras.layers.Dense(128, activation = 'relu'))
model.add(tf.keras.layers.Dense(1))

model.compile(loss = tf.keras.losses.BinaryCrossentropy(from_logits = True), optimizer = 'adam', metrics = ['accuracy'])

In [102]:
train_data = packed_train_data.shuffle(500)
test_data = packed_test_data

In [105]:
model.fit(train_data, epochs = 20)

Epoch 1/20
126/126 [==============================] - 1s 9ms/step - loss: 0.2661 - accuracy: 0.8820
Epoch 2/20
126/126 [==============================] - 1s 8ms/step - loss: 0.2674 - accuracy: 0.8804
Epoch 3/20
126/126 [==============================] - 1s 7ms/step - loss: 0.2630 - accuracy: 0.8884
Epoch 4/20
126/126 [==============================] - 1s 7ms/step - loss: 0.2658 - accuracy: 0.8884
Epoch 5/20
126/126 [==============================] - 1s 7ms/step - loss: 0.2647 - accuracy: 0.8772
Epoch 6/20
126/126 [==============================] - 1s 6ms/step - loss: 0.2619 - accuracy: 0.8884
Epoch 7/20
126/126 [==============================] - 1s 5ms/step - loss: 0.2616 - accuracy: 0.8788
Epoch 8/20
126/126 [==============================] - 1s 6ms/step - loss: 0.2584 - accuracy: 0.8804
Epoch 9/20
126/126 [==============================] - 1s 6ms/step - loss: 0.2637 - accuracy: 0.8788
Epoch 10/20
126/126 [==============================] - 1s 6ms/step - loss: 0.2558 - accuracy: 0.8804

In [107]:
test_loss, test_accuracy = model.evaluate(test_data)

     53/Unknown - 1s 11ms/step - loss: 0.6501 - accuracy: 0.8371

In [110]:
predictions = model.predict(test_data)

# Show some results
for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
  prediction = tf.sigmoid(prediction).numpy()
  print("Predicted survival: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("SURVIVED" if bool(survived) else "DIED"))


Predicted survival: 0.62%  | Actual outcome:  DIED
Predicted survival: 14.63%  | Actual outcome:  DIED
Predicted survival: 24.55%  | Actual outcome:  DIED
Predicted survival: 4.27%  | Actual outcome:  DIED
Predicted survival: 6.51%  | Actual outcome:  SURVIVED
